### ISSUE TITLE
Processing stuck 

### ISSUE THREAD

**Issue by YaroslavShchekaturov** [3DOM-FBK/COLMAP_SLAM#4]
Hi Luca!

Thank you for your great work! While running python main.py. processing always gets stuck at some point and after that, I get only 
![image](https://github.com/3DOM-FBK/COLMAP_SLAM/assets/22734034/815c8401-7833-4304-915d-79a257b6001e)

Have you ever seen something like that ?

**Comment by lcmrl** [comment]
Hi, so it works fine but after several minutes you have this error right?

**Comment by YaroslavShchekaturov** [comment]
Hi Luca, 

I found that the process gets stuck usually when it reaches the last image.

**Comment by YaroslavShchekaturov** [comment]
![image](https://github.com/3DOM-FBK/COLMAP_SLAM/assets/22734034/59e6dc13-b80f-4201-9bd8-5f8090f9fffc)

**Comment by lcmrl** [comment]
The problem is that for now when the simulator finishes to replay the sequence it stops the application. The default behaviour is guided by  `FORCE_PROCESS_ALL_FRAMES = True`, but if keyframe selection and keyframes orientation are too slow you can have a delay, and the application stops before finishing to process all the frames. To really go "real-time" you have to set `FORCE_PROCESS_ALL_FRAMES ` to False.

So, could you check if changing in the config.ini file `FORCE_PROCESS_ALL_FRAMES = False` it works?
If you have still problem, please try to skip some images like this:
```
STEP = 4
SIMULATOR_SLEEP_TIME = 0.2
```

**Comment by lcmrl** [comment]
I hope the issue is solved, please feel free to send any suggestions or open other issues. Any collaboration in improving and optimizing is very helpful, in the case you can fork and push your changes

**Comment by YaroslavShchekaturov** [comment]
Dear Luca,
Thank you very much for your response. Everything works perfectly right now.
