### ISSUE TITLE
LOOP_CLOSURE_DETECTION = True

### ISSUE THREAD

**Issue by YaroslavShchekaturov** [3DOM-FBK/COLMAP_SLAM#5]
Hi !

I just tried to run the code with LOOP_CLOSURE_DETECTION = True and set RootSIFT. Changed this part
![image](https://github.com/3DOM-FBK/COLMAP_SLAM/assets/22734034/c9ad7831-b5b6-4d3e-9be4-a42fbf025fe8)

In general, everything goes fine, I've downloaded VOCAB_TREE. The one thing that bothers me is that sometimes I get outliers. Am I doing anything wrong? 
![image](https://github.com/3DOM-FBK/COLMAP_SLAM/assets/22734034/4b936476-5038-45fd-8eac-a8a034e69315)

**Comment by lcmrl** [comment]
Hi, do you still have the problem?

**Comment by YaroslavShchekaturov** [comment]
Hi! 

Yes, it usually happens in a changing lighting condition when the algorithm fails to align the image.

**Comment by lcmrl** [comment]
Yes it is because the erroneous detection of a loop closure. For how it is implemented now I think you can only play with the commented options, but I do not think they will help a lot
![image](https://github.com/3DOM-FBK/COLMAP_SLAM/assets/93863149/9bd5cd3a-a65f-4c68-a36a-d418f4a0d7e2)

The solution is in doing loop-closure detection with deep approaches, but not implemented yet in colmap-slam. For offline processing you could try to use this repo https://github.com/3DOM-FBK/deep-image-matching where for instance you can use deep image retrieval that is more robust for loop closure detection.

**Comment by YaroslavShchekaturov** [comment]
got it! Thank you very much!

**Comment by lcmrl** [comment]
Good, if you find any problems do not hesitate to open an issue or if you want to collaborate on the project simply edit and ask for merging changes, any help is welcome!
